# Generated by Django 5.1.6 on 2025-02-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_address_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
