# Generated by Django 5.1.6 on 2025-03-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_description_servicecategory_description'),
        ('users', '0006_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.service'),
        ),
    ]
