# Generated by Django 5.1.6 on 2025-03-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_profile_image_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
