# Generated by Django 5.1.6 on 2025-03-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='background_check_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='badges_earned',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='booking_history',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location_longitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_payment_method',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_services',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_completed_tasks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='years_of_experience',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
