# Generated by Django 5.1.6 on 2025-03-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_address_profile_availability_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='profile',
            name='availability_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_payment_method',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('Paypal', 'Paypal')], default='mpesa', max_length=50),
        ),
    ]
