# Generated by Django 5.1.6 on 2025-04-05 20:05

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_booking'),
        ('users', '0017_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 4, 5, 22, 5, 46, 467620, tzinfo=datetime.timezone.utc))])),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, limit_choices_to={'role': 'service_provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('provider', 'date'), name='unique_provider_booking_time'), models.UniqueConstraint(condition=models.Q(('date__gte', datetime.datetime(2025, 4, 4, 20, 5, 46, 467620, tzinfo=datetime.timezone.utc)), ('status__in', ['pending', 'confirmed'])), fields=('user', 'date'), name='max_two_bookings_per_day')],
            },
        ),
    ]
