# Generated by Django 5.1.6 on 2025-04-05 20:07

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_booking'),
        ('users', '0018_booking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='max_two_bookings_per_day',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 4, 5, 22, 7, 19, 136121, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'service_provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.profile'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('date__gte', datetime.datetime(2025, 4, 4, 20, 7, 19, 136121, tzinfo=datetime.timezone.utc)), ('status__in', ['pending', 'confirmed'])), fields=('user', 'date'), name='max_two_bookings_per_day'),
        ),
    ]
