# Generated by Django 5.1.6 on 2025-04-06 05:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_booking'),
        ('users', '0020_remove_booking_max_two_bookings_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='max_two_bookings_per_day',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 4, 6, 7, 49, 9, 835637, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('date__gte', datetime.datetime(2025, 4, 5, 5, 49, 9, 835637, tzinfo=datetime.timezone.utc)), ('status__in', ['pending', 'confirmed'])), fields=('user', 'date'), name='max_two_bookings_per_day'),
        ),
    ]
