# Generated by Django 5.1.6 on 2025-04-06 06:56

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_booking'),
        ('users', '0021_remove_booking_max_two_bookings_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='services/booking_attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='max_two_bookings_per_day',
        ),
        migrations.AddField(
            model_name='booking',
            name='urgency_level',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 4, 6, 8, 56, 25, 620093, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bookingattachment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_files', to='users.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='related_bookings', to='users.bookingattachment'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('date__gte', datetime.datetime(2025, 4, 5, 6, 56, 25, 620093, tzinfo=datetime.timezone.utc)), ('status__in', ['pending', 'confirmed'])), fields=('user', 'date'), name='max_two_bookings_per_day'),
        ),
    ]
