# Generated by Django 5.1.6 on 2025-04-07 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_booking'),
        ('users', '0023_remove_booking_max_two_bookings_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='max_two_bookings_per_day',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('bidding', 'Open for Bidding'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='bidding', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('date__gte', datetime.datetime(2025, 4, 6, 19, 43, 11, 464192, tzinfo=datetime.timezone.utc)), ('status__in', ['pending', 'confirmed'])), fields=('user', 'date'), name='max_two_bookings_per_day'),
        ),
    ]
