# Generated by Django 5.1.6 on 2025-04-10 13:01

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_booking'),
        ('users', '0026_remove_booking_max_two_bookings_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='services/booking_attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('punctuality', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('quality', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('professionalism', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('provider_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='max_two_bookings_per_day',
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('date__gte', datetime.datetime(2025, 4, 9, 13, 0, 59, 184221, tzinfo=datetime.timezone.utc)), ('status__in', ['pending', 'confirmed'])), fields=('user', 'date'), name='max_two_bookings_per_day'),
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.booking'),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.booking'),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='proof_images',
            field=models.ManyToManyField(to='users.proofimage'),
        ),
        migrations.AddField(
            model_name='proofimage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completion_files', to='users.taskcompletion'),
        ),
    ]
