# Generated by Django 5.1.6 on 2025-04-11 06:01

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_booking'),
        ('users', '0028_remove_booking_max_two_bookings_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='max_two_bookings_per_day',
        ),
        migrations.AlterField(
            model_name='proofimage',
            name='file',
            field=models.FileField(upload_to='services/task_completion_attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='proofimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='proof_images',
            field=models.ManyToManyField(blank=True, related_name='related_taskCompletions', to='users.proofimage'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('date__gte', datetime.datetime(2025, 4, 10, 6, 1, 26, 327183, tzinfo=datetime.timezone.utc)), ('status__in', ['pending', 'confirmed'])), fields=('user', 'date'), name='max_two_bookings_per_day'),
        ),
    ]
