# Generated by Django 5.1.6 on 2025-03-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'ServiceCategory', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, default='services/user-default.png', null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.FileField(blank=True, default='categories/user-default.png', null=True, upload_to='categories/'),
        ),
    ]
