# Generated by Django 5.1.6 on 2025-03-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicecategory_options_service_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
