# Generated by Django 5.1.6 on 2025-04-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
